polarity-lang/polarity

Cargo.lock, app/Cargo.toml, app/src/cli/mod.rs
Fixes #149 
I had to rename the module from "app" to "polarity", since `clap` uses the name of the module to generate the output.
```console
>pol --version
polarity 0.1.0
>pol --help
Usage: pol [OPTIONS] <COMMAND>
Commands:
run     Run a source code file
fmt     Format a code file
texify  Render a code file as a latex document
xfunc   De-/Refunctionalize a type in a code file
lsp     Start an LSP server
lift    Lift local (co)matches of a type to the top-level
help    Print this message or the help of the given subcommand(s)
Options:
--trace    Enable internal debug output
-h, --help     Print help
-V, --version  Print version
```
=> Add version subcommand; rename module from app to polarity

examples/boolrep.pol, examples/colist.pol, examples/covect.pol, examples/example.pol, examples/simple.pol, examples/typedhole.pol, examples/vect.pol, lang/lifting/src/lib.rs, lang/lowering/src/imp.rs, lang/parser/src/cst.rs, lang/parser/src/grammar/cst.lalrpop, lang/printer/src/ust.rs, lang/query/src/view/rt.rs, lang/syntax/src/trees/forget/tst.rs, lang/syntax/src/trees/generic/def.rs, lang/syntax/src/trees/generic/fold.rs, lang/syntax/src/trees/generic/map.rs, lang/syntax/src/trees/generic/visit.rs, lang/typechecker/src/typecheck.rs, lang/xfunc/src/matrix.rs, test/suites/fail-check/002.pol, test/suites/fail-check/003.pol, test/suites/fail-check/004.pol
Having a toplevel expression in a file doesn't fit into our future plans where we plan to introduce toplevel definitions (cp 
#12) and module imports.
=> Remove toplevel expression

CHANGELOG.md, CONTRIBUTING.md
We should get a little bit more careful about versioning and releasing now.
Here is what I think are some minimal first steps:
- Add an (empty) changelog.
- Add some information about the PR and release workflow.
Should we specify a merge strategy for PRs (rebase / squash / merge etc?)
=> Add information about contributing and releases

.github/workflows/ci.yml
The `actions-rs` organization is sadly dead and all their GitHub repos are archived. So we should move away from them.
For the toolchain action there is a replacement by dtolnay, and I think we can just replace the `actions-rs/cargo` action by a run step.
=> Bump rust actions

app/src/cli/check.rs, app/src/cli/mod.rs, app/src/cli/run.rs, examples/vect.pol, lang/query/src/view/rt.rs, lang/syntax/src/trees/generic/def.rs
```console
david@anaxes ~/polarity/polarity (add-main-functions)$ pol run examples/vect.pol 
examples/vect.pol typechecked successfully!
Cons(S(S(S(Z))), Z, Cons(S(S(Z)), Z, Cons(S(Z), Z, Cons(Z, Z, Nil))))
```
=> Implement main expressions

lang/elaborator/src/normalizer/env.rs, lang/elaborator/src/normalizer/val.rs, lang/elaborator/src/unifier/unify.rs, lang/lifting/src/fv.rs, lang/printer/src/generic.rs, lang/syntax/src/common/de_bruijn.rs, lang/syntax/src/common/subst.rs, lang/syntax/src/ctx/values.rs, lang/syntax/src/trees/generic/fold.rs, lang/syntax/src/trees/ust/shift.rs, lang/syntax/src/trees/ust/subst.rs
Small PR :) Basically I was a bit confused about how the `ShiftInRange` and `Shift` traits interact.
~~It is still WIP because I want to write a bit more documentation about the expected invariant, which isn't documented at the moment.~~ Edit: I added some unit tests and more comments explaining the range and how to implement shift correctly.
=> Unify ShiftInRange and Shift traits

lang/query/src/index.rs, lang/query/src/info.rs, lang/query/src/info/collect.rs, lang/query/src/info/data.rs, lang/query/src/info/mod.rs, lang/query/src/view/spans.rs, util/lsp/src/hover.rs, util/lsp/src/lib.rs, util/lsp/src/server.rs
Previously we only generated hover information from the "TypeInfo" field which was annotated in various expressions. This had the downside that we could not print specific information about the syntax node, for example if it is a bound variable or a constructor, or a typed hole, etc.
I have rewritten a huge chunk of the `type-on-hover` functionality so that we now display additional information when you hover over a syntax node.
Currently the only additional information is the "kind" of syntax node, but we can add more information in the future, for example the doc strings.
=> Improve type-on-hover

lang/elaborator/src/typechecker/typecheck.rs, lang/lifting/src/lib.rs, lang/lowering/src/lower/exp.rs, lang/printer/src/generic.rs, lang/renaming/src/ast.rs, lang/renaming/src/ctx.rs, lang/syntax/src/ctx/map.rs, lang/syntax/src/trees/generic/decls.rs, lang/syntax/src/trees/generic/exp.rs, lang/syntax/src/trees/generic/lookup.rs, lang/syntax/src/trees/tst/def.rs, lang/syntax/src/trees/tst/forget.rs, lang/syntax/src/trees/ust/def.rs, lang/syntax/src/trees/ust/util.rs, test/test-runner/src/phases.rs
I restrained myself to one commit for this PR :D This is the commit which finally completely removes the Phase annotation. Afterwards there is still some clean up and refactoring to do, but I wanted to keep those separate.
=> Remove Phases from syntax representation

Cargo.lock, lang/elaborator/src/normalizer/eval.rs, lang/elaborator/src/normalizer/read_back.rs, lang/elaborator/src/normalizer/val.rs, lang/elaborator/src/typechecker/typecheck.rs, lang/lifting/src/lib.rs, lang/lowering/src/lower/exp.rs, lang/query/src/info/collect.rs, lang/query/src/info/data.rs, lang/renaming/src/ast.rs, lang/syntax/src/trees/generic/exp.rs, lang/syntax/src/trees/generic/subst.rs, util/lsp/Cargo.toml, util/lsp/src/codeactions.rs, util/lsp/src/format.rs, util/lsp/src/hover.rs, util/lsp/src/lib.rs, util/lsp/src/server.rs
The information whether a `Call` stands for a constructor, codefinition or toplevel definition is currently not recorded in the AST, but has to be reconstructed by looking up in the context what the name refers to. (Similarly for `DotCall` which can stand for destructors or codefinitions). 
This PR annotates the AST with `CallKind` resp. `DotCallKind` and uses this information to display more accurate information on hover.
Other small  refactorings:
- Put the `formatting` and `codeactions` implementations of the LSP server into their own modules.
- Rename `Ctor` and `Dtor` in the evaluator to `Call` and `DotCall` in order to be consistent with the other AST representations.
=> Annotate CallKind and DotCallKind in AST

Cargo.lock, lang/elaborator/src/typechecker/decls.rs, lang/lifting/src/lib.rs, lang/lowering/src/lib.rs, lang/parser/Cargo.toml, lang/parser/src/cst/decls.rs, lang/parser/src/grammar/cst.lalrpop, lang/parser/src/lib.rs, lang/query/Cargo.toml, lang/query/src/view/rt.rs, lang/renaming/src/ast.rs, lang/syntax/Cargo.toml, lang/syntax/src/trees/ast/decls.rs, lang/syntax/src/trees/ast/lookup.rs, test/test-runner/Cargo.toml, test/test-runner/src/phases.rs, test/test-runner/src/runner.rs
Each module knows to which file it corresponds on disk. This PR replaces #198 .
I need this information in order to implement the "jump-to" functionality in the  LSP  server correctly. Url is the type that the LSP protocol uses everywhere, so I use that one instead of PathBuf, OsPath or something similar.
=> Put Url containing absolute path into definition of modules

Cargo.lock, lang/elaborator/Cargo.toml, lang/lifting/Cargo.toml, lang/lowering/Cargo.toml, lang/parser/Cargo.toml, lang/query/Cargo.toml, lang/renaming/Cargo.toml, lang/syntax/Cargo.toml, lang/xfunc/Cargo.toml, util/lsp/Cargo.toml, util/miette_util/Cargo.toml
The codespan library made the unfortunate decision to practice information hiding. We therefore have to fork the library in order to access the internal structure of `File`.
I could also move the fork to the polarity repo , if you prefer that @timsueberkrueb
=> Use a fork of codespan

lang/query/src/info/collect.rs, lang/query/src/info/data.rs, lang/query/src/info/item.rs, lang/query/src/info/mod.rs, lang/query/src/lib.rs, lang/query/src/view/spans.rs, lang/query/src/view_mut.rs, util/lsp/src/hover.rs
Fixes #64
Allows to hover over all kinds of syntax nodes, and displays basic information about that specific syntax node. Should be extended with more info in the future, of course.
=> Add hover information for many more syntax nodes

lang/query/src/lib.rs, lang/query/src/view/mod.rs, lang/query/src/view/rt.rs, lang/query/src/view/spans.rs, lang/query/src/view_mut.rs, util/lsp/src/codeactions.rs, util/lsp/src/format.rs, util/lsp/src/hover.rs, util/lsp/src/server.rs
We no longer depend on the `FileId` type from the codespan library but use the `Url` type everywhere to index the Hashmaps of the query crate. This is simpler, because we always communicate using the `Url` type with the LSP server.
=> Use Url as index into Hashmaps in query crate

examples/stlc.pol, util/lsp/src/hover.rs
Slightly change the text that is displayed when hovering over `Type`. I also added a lot of doccomments to the `stlc.pol` example, because I will need them when I start testing the improved type-on-hover functionality.
=> Add some docs to stlc example

lang/query/src/info/collect.rs, lang/query/src/info/data.rs, util/lsp/src/capabilities.rs, util/lsp/src/gotodefinition.rs, util/lsp/src/hover.rs, util/lsp/src/lib.rs, util/lsp/src/server.rs
Implements the jump-to-definition feature for `TypCtor`, `Call` and `DotCall` in the program.
The ability to have access to the decl hashmap in the collector will also enable the feature to show the docstrings on hover, but that is for another PR :)
=> Jump to definition

lang/elaborator/src/normalizer/eval.rs, lang/elaborator/src/normalizer/read_back.rs, lang/elaborator/src/normalizer/val.rs, lang/elaborator/src/typechecker/decls.rs, lang/elaborator/src/typechecker/typecheck.rs, lang/lifting/src/lib.rs, lang/lowering/src/ctx.rs, lang/lowering/src/lib.rs, lang/lowering/src/lower/exp.rs, lang/query/src/info/collect.rs, lang/query/src/info/data.rs, lang/renaming/src/ast.rs, lang/syntax/src/trees/ast/decls.rs, lang/syntax/src/trees/ast/exp.rs, lang/syntax/src/trees/ast/ident.rs, lang/syntax/src/trees/ast/subst.rs, util/lsp/src/hover.rs
Since implementing the whole implicit arguments story in one go is probably too much work, I propose this as a first step. It basically amounts to generating fresh unique ids for every `?` contained in the source program, and to register them at the module level as well.
=> Add metavariables

lang/elaborator/src/normalizer/eval.rs, lang/elaborator/src/normalizer/val.rs, lang/elaborator/src/typechecker/decls/codefinition.rs, lang/elaborator/src/typechecker/decls/definition.rs, lang/elaborator/src/typechecker/exprs/local_comatch.rs, lang/elaborator/src/typechecker/exprs/local_match.rs, lang/lifting/src/fv.rs, lang/lifting/src/lib.rs, lang/lowering/src/lower/decls.rs, lang/lowering/src/lower/exp.rs, lang/parser/src/cst/decls.rs, lang/parser/src/cst/exp.rs, lang/parser/src/grammar/cst.lalrpop, lang/printer/src/generic.rs, lang/query/src/info/collect.rs, lang/renaming/src/ast.rs, lang/syntax/src/ast/decls.rs, lang/syntax/src/ast/exp.rs, lang/xfunc/src/matrix.rs
Removes the `Match` construct from the AST and CST. The `Match` construct was just a wrapper around a vector of `Case` and the `omit_absurd` boolean.
This leads to unnecessary indirection and makes the code harder to understand, especially since `Match` is not a semantic concept of our domain, i.e. it does not have any independent meaning outside of a `LocalMatch` or `LocalComatch`.
=> Remove match

Cargo.lock, lang/parser/Cargo.toml, lang/parser/src/grammar/cst.lalrpop, lang/parser/src/lexer/mod.rs, lang/parser/src/lib.rs, lang/parser/src/result.rs, test/suites/fail-parse/P-001.expected, test/suites/fail-parse/P-002.expected, test/suites/fail-parse/P-003.expected
In order to use namespaced identifiers `foo::bar::baz` we have to rewrite the lexer. The current lexer which is hardwired into `lalrpop` automatically skips whitespace, but we dont want to accept whitespace between the tokens from the example: `"foo" + "::" + "bar" + "::" + "baz"`, i.e. we don't want to accept `foo :: bar:: baz` or something like it.
I just followed the LALRPOP tutorial here: http://lalrpop.github.io/lalrpop/lexer_tutorial/005_external_lib.html
=> Add a custom lexer

test/test-runner/src/main.rs, test/test-runner/src/phases.rs, test/test-runner/src/runner.rs
Removed the debug functionality and the `Report` type which is no longer necessary. Changes how the results are printed on the command line. Example output:
```console
Suite "fail-check":
- 005                                      ✓
- Regression-86                            ✓
- 002                                      ✓
- 003                                      ✓
- 004                                      ✓
- 001                                      ✓
6/6 successful
Suite "success":
- Regression-230b                          ✓
- 015                                      ✓
- 005                                      ✓
- 009                                      ✓
- Regression-137                           ✓
- Regression-230                           ✓
- 013 …
```
=> Remove debug option

lang/elaborator/src/typechecker/exprs/mod.rs, lang/lifting/src/fv.rs, lang/lifting/src/lib.rs, lang/lowering/src/lower/decls.rs, lang/parser/src/cst/decls.rs, lang/parser/src/grammar/cst.lalrpop, lang/parser/src/lexer/mod.rs, lang/printer/src/generic.rs, lang/printer/src/tokens.rs, lang/renaming/src/ast.rs, lang/syntax/src/ast/decls.rs
Allows to parse, lower and print implicit parameters in declarations. Does not have any effect yet. Also wrote some tests and documentation.
Related to #237
=> Add implicit params

lang/elaborator/src/normalizer/eval.rs, lang/elaborator/src/normalizer/val.rs, lang/elaborator/src/typechecker/decls/codefinition.rs, lang/elaborator/src/typechecker/decls/definition.rs, lang/elaborator/src/typechecker/exprs/local_comatch.rs, lang/elaborator/src/typechecker/exprs/local_match.rs, lang/lifting/src/lib.rs, lang/lowering/src/lower/decls.rs, lang/lowering/src/lower/exp.rs, lang/parser/src/cst/decls.rs, lang/parser/src/cst/exp.rs, lang/parser/src/grammar/cst.lalrpop, lang/parser/src/lexer/mod.rs, lang/printer/src/generic.rs, lang/renaming/src/ast.rs, lang/syntax/src/ast/decls.rs, lang/syntax/src/ast/exp.rs, lang/xfunc/src/matrix.rs, test/suites/success/011.pol, test/suites/success/012.pol
This allows to simplify the implementation of the elaborator for matches and comatches. I have also factored the exhaustiveness checking into separate functions.
=> Remove the omit_absurd feature

lang/elaborator/src/typechecker/exprs/local_comatch.rs, lang/elaborator/src/typechecker/exprs/local_match.rs
Here is the background for this PR: Unification is currently implemented in a way that is subtly wrong, and that will definitely break in the future when we extend it. The problem is that the unification algorithm assumes that there is only one `LevelCtx` which is valid for all constraints. What we should do instead is to make the `LevelCtx` part of each individual constraint. In order to do this we have to move the generation of the constraints in the inference of the `local_match` and `local_comatch` functions syntactically close to the call of `unify(...)` , and essentially under the context extension `check_telescope`, so that we can correctly annotate the constraints with the correct context in the future.
=> Refactor local match inference

lang/elaborator/src/typechecker/exprs/local_comatch.rs, lang/elaborator/src/typechecker/exprs/local_match.rs, lang/elaborator/src/typechecker/util.rs, lang/elaborator/src/unifier/constraints.rs, lang/elaborator/src/unifier/mod.rs, lang/elaborator/src/unifier/unify.rs
The main difference is that we go from:
```rust
pub struct Eqn {
pub lhs: Rc<Exp>,
pub rhs: Rc<Exp>,
}
```
to
```rust
/// A constraint that can be solved by the constraint solver.
#[derive(Debug, Clone, Eq, PartialEq, Hash)]
pub enum Constraint {
/// An equality constraint between two expressions.
Equality { lhs: Rc<Exp>, rhs: Rc<Exp> },
/// An equality constraint between two argument lists.
EqualityArgs { lhs: Args, rhs: Args },
}
```
The motivation is that once we have made the `LevelCtx` a part of `Constraint`, we will have the following function invariant:
- If `unify(constraint) = Some(substitution)`, then the domain of the substitution is a subset of the LevelCtx of the constraint.
In order to express this invariant we are only allowed to pass exactly one constraint to `unify`, and …
=> Refactor constraints

lang/elaborator/src/normalizer/env.rs, lang/lowering/src/ctx.rs, lang/syntax/src/ctx/levels.rs
Turns the level context into a `Vec<Vec<()>>` instead of a `Vec<usize>`. This is necessary so that we can unify all existing contexts as `Vec<Vec<a>>`.
=> Make level context consistent with other contexts

lang/elaborator/src/normalizer/env.rs, lang/elaborator/src/normalizer/eval.rs, lang/elaborator/src/normalizer/normalize.rs, lang/elaborator/src/unifier/unify.rs, lang/renaming/src/ast.rs, lang/renaming/src/ctx.rs, lang/syntax/src/ast/exp.rs, lang/syntax/src/ast/traits/occurs.rs, lang/syntax/src/ctx/def.rs, lang/syntax/src/ctx/levels.rs, lang/syntax/src/ctx/values.rs
Use a generic implementation `pub struct GenericCtx<T> { bounds: Vec<Vec<T>> }` for contexts. This allows to remove some duplication, e.g. the implementation of `idx_to_lvl` and `lvl_to_idx` was the same for all 4 contexts, but the code couldn't be shared before.
=> Use generic ctx

Cargo.lock, Cargo.toml, README.md, app/Cargo.toml, app/src/cli/mod.rs, app/src/main.rs, test/test-runner/Cargo.toml, test/test-runner/src/main.rs
Builds upon your commit and adds the same functionality to the test-runner. Also some minor cleanup w.r.t. dependencies and the README.
=> Make tracing configurable

examples/imports.pol, lang/ast/src/decls.rs, lang/elaborator/src/typechecker/decls/mod.rs, lang/lifting/src/lib.rs, lang/lowering/src/lib.rs, lang/lowering/src/lookup_table.rs, lang/lowering/src/lower/decls.rs, lang/parser/src/cst/decls.rs, lang/parser/src/grammar/cst.lalrpop, lang/parser/src/lexer/mod.rs, lang/parser/src/lib.rs, lang/printer/src/tokens.rs, lang/query/src/view/xfunc.rs, lang/renaming/src/ast.rs
I slightly changed the `cst` representation that you chose, and made the `ast` definition of modules consistent with that.
It should not be too hard to rebase #283 on top of this PR.
=> Parse and prettyprint use declarations

web/packages/app/src/tutorial/highlight.ts
The demo on the website does not highlight the correct keywords. This will be a hotfix for that issue.
=> Fix prettyprinting of keywords in browser

lang/ast/src/decls.rs, lang/elaborator/src/lib.rs, lang/elaborator/src/result.rs, lang/elaborator/src/typechecker/lookup_table.rs, lang/lowering/src/lookup_table.rs, lang/lowering/src/result.rs, lang/parser/src/lexer/mod.rs
Adjusts the string literals lexer to not store the quotation marks, and add some instances of Clone and Debug to types.
=> Adjust stringlit lexer

lang/parser/src/lexer/mod.rs
Happy for any other suggestions :)
=> Use unicode categories for the definition of identifiers in the lexer

lang/ast/src/exp.rs, lang/ast/src/ident.rs, lang/elaborator/src/normalizer/eval.rs, lang/elaborator/src/normalizer/val.rs, lang/elaborator/src/typechecker/ctx.rs, lang/elaborator/src/typechecker/exprs/hole.rs, lang/lifting/src/lib.rs, lang/lowering/src/lower/exp.rs, lang/parser/src/cst/exp.rs, lang/parser/src/grammar/cst.lalrpop, lang/printer/src/tokens.rs, lang/query/src/info/collect.rs, lang/renaming/src/ast.rs, test/suites/fail-check/007.pol, test/suites/fail-parse/Regr-underscore.pol, test/suites/success/017.pol, test/suites/success/018.pol
=> Implement different kinds of typed holes

lang/ast/src/decls.rs, lang/ast/src/exp.rs, lang/ast/src/ident.rs, lang/ast/src/traits/subst.rs, lang/elaborator/src/normalizer/env.rs, lang/elaborator/src/normalizer/val.rs, lang/elaborator/src/typechecker/exprs/local_comatch.rs, lang/elaborator/src/typechecker/exprs/local_match.rs, lang/elaborator/src/typechecker/exprs/mod.rs, lang/lifting/src/lib.rs, lang/lowering/src/ctx.rs, lang/lowering/src/lower/decls/codata_declaration.rs, lang/lowering/src/lower/decls/codefinition.rs, lang/lowering/src/lower/decls/data_declaration.rs, lang/lowering/src/lower/decls/definition.rs, lang/lowering/src/lower/decls/mod.rs, lang/lowering/src/lower/decls/toplevel_let.rs, lang/lowering/src/lower/exp/mod.rs, lang/query/src/info/collect.rs, lang/query/src/info/data.rs, lang/query/src/xfunc.rs, lang/renaming/src/ctx.rs, lang/renaming/src/util.rs, lang/xfunc/src/lib.rs
Pretty boring, and there is a lot of potential for API cleanup, but having an abstract Ident type for the AST is necessary to annotate it with origin information (i.e. in which module it was defined).
=> Make ast Ident abstract

.github/workflows/ci.yml, Cargo.toml, app/Cargo.toml, lang/ast/Cargo.toml, lang/elaborator/Cargo.toml, lang/lifting/Cargo.toml, lang/lowering/Cargo.toml, lang/lsp/Cargo.toml, lang/miette_util/Cargo.toml, lang/parser/Cargo.toml, lang/printer/Cargo.toml, lang/query/Cargo.toml, lang/renaming/Cargo.toml, lang/xfunc/Cargo.toml
Fixes #299 
The error message now looks like this if the version of `rustc`is too old:
```console
error: rustc 1.80.0 is not supported by the following packages:
ast@0.1.0 requires rustc 1.81
elaborator@0.1.0 requires rustc 1.81
lifting@0.1.0 requires rustc 1.81
lowering@0.1.0 requires rustc 1.81
lsp-server@0.1.0 requires rustc 1.81
miette_util@0.1.0 requires rustc 1.81
parser@0.1.0 requires rustc 1.81
parser@0.1.0 requires rustc 1.81
parser@0.1.0 requires rustc 1.81
polarity@0.1.0 requires rustc 1.81
printer@0.1.0 requires rustc 1.81
query@0.1.0 requires rustc 1.81
renaming@0.1.0 requires rustc 1.81
xfunc@0.1.0 requires rustc 1.81
```
=> Add MSRV 1.80

lang/lowering/src/ctx.rs, lang/lowering/src/lib.rs, lang/lowering/src/lookup_table.rs, lang/lowering/src/result.rs, lang/query/src/database.rs
First step of reimplementing the logic for multi-module lowering. The logic for combining multiple lowering lookup tables should reside in the driver, not in the lowering module.
=> Reimplement multi module lowering (1/n)

Cargo.lock, lang/lowering/Cargo.toml, lang/lowering/src/ctx.rs, lang/lowering/src/lib.rs, lang/lowering/src/lookup_table/build.rs, lang/lowering/src/lookup_table/lookup.rs, lang/lowering/src/lookup_table/mod.rs, lang/lowering/src/lower/exp/mod.rs, lang/lowering/src/symbol_table/build.rs, lang/lowering/src/symbol_table/lookup.rs, lang/lowering/src/symbol_table/mod.rs, lang/query/src/database.rs, test/test-runner/src/phases.rs
Introduces the new type `ModuleLookupTable` which contains information about all the symbols declared in one specific module.
The semantics is currently:
- You can have multiple imports which define the same symbol. In that case, the symbol resolves to the first symbol found in the hashmaps. In the future we probably want to throw an ambiguous occurrence warning.
=> Reimplement multi module lowering (4/n)

lang/xfunc/src/matrix.rs
Building the matrices was way too complicated. This was an artefact of the old representation where the Xtors were not part of the data/codata type node.
=> Simplify xfunc matrix

lang/lowering/src/ctx.rs
Only `bind_fold` and `bind_single` are ever used during lowering.  The functions `bind_fold2`, `bind_fold_failable` and `bind_iter` are therefore just verbose wrappers which can be inlined.
=> Simplify lowering folds

lang/ast/src/exp/args.rs, lang/ast/src/exp/call.rs, lang/ast/src/exp/dot_call.rs, lang/ast/src/exp/typ_ctor.rs
This fixes a bug which occurs if we print a list of arguments which consist only of implicitly inserted arguments. An example of this is `Nil` which has one implicitly inserted argument for the type. Before this fix we would print `Nil()`, and after the fix we will print `Nil`.
=> Fix prettyprinter bug for lists of implicitly inserted arguments

app/src/cli/mod.rs
New output:
```console
> pol
Usage: pol [OPTIONS] <COMMAND>
Commands:
run     Run the main expression of a file
check   Typecheck a file
fmt     Format a code file
texify  Render a code file as a latex document
xfunc   De-/Refunctionalize a type in a code file
lift    Lift local (co)matches of a type to the top-level
help    Print this message or the help of the given subcommand(s)
Options:
--trace    Enable trace logging
--debug    Enable debug logging
-h, --help     Print help
-V, --version  Print version
```
=> Hide "pol lsp" subcommand

Makefile
This works, but only takes into account the tests configured inside the workspace, and doesn't run the testrunner. I have to figure out how to include the coverage generated from running the testsuite as well.
=> Add Makefile target for computing code coverage

.github/workflows/examples-index.yml, examples/index.json, scripts/check_examples_index.sh, scripts/git-hooks/pre-commit
This index file will determine the names of examples displayed in the example selection on the website. It is currently generated by a script in the website repo based on the filenames alone. By manually specifying the index, we can improve the titles displayed to the user.
@BinderDavid please feel free to improve the titles by pushing to this branch.
After this has been merged, we can remove the script from the website repo.
=> Add examples/index.json

Cargo.lock, Cargo.toml, app/Cargo.toml, contrib/nix/package.nix, lang/lsp/Cargo.toml, lang/lsp/src/capabilities.rs, lang/lsp/src/codeactions.rs, lang/lsp/src/conversion/mod.rs, lang/lsp/src/conversion/uri_to_url.rs, lang/lsp/src/format.rs, lang/lsp/src/gotodefinition.rs, lang/lsp/src/hover.rs, lang/lsp/src/server.rs, web/crates/browser/Cargo.toml, web/package-lock.json, web/package.json, web/packages/app/declarations.d.ts, web/packages/app/package.json, web/packages/app/src/editor/app.ts, web/packages/app/src/editor/language-configuration.json, web/packages/app/src/editor/language.ts, web/packages/app/src/editor/pol.tmLanguage.json, web/packages/app/src/editor/workers.ts, web/packages/app/webpack.config.js
The purpose of this PR is twofold:
1. Upgrade `tower-lsp` to use the latest [community fork](https://github.com/tower-lsp/tower-lsp) commit. The original `tower-lsp` library is unmaintained and the maintainer is unresponsive.
2. Upgrade the web demo to use a more up-to-date VS Code/Monaco. This brings us closer to reusing (parts of) the VS Code extension for the web demo. As a starting point, in this PR I copied the language configuration and TextMate grammer from the extension repository. This can be deduplicated in the future.
=> Upgrade web demo and tower-lsp

.github/workflows/nix.yml, contrib/nix/shell.nix
Previously `nix develop` + `make test` would lead to an error while building `openssl-probe` dependency.
A similar error is described in https://nixos.wiki/wiki/Rust#Building_Rust_crates_that_require_external_system_libraries.
This PR also adds a CI run to test the nix shell.
=> Fix nix development shell

Cargo.lock, lang/backend/Cargo.toml, lang/backend/src/ir/decls.rs, lang/backend/src/ir/exprs.rs
Cherry-picked two commits from #426 which add `Print` instances to the IR and a Zero-sized term.
=> Prettyprint ir

lang/driver/src/info/collect.rs, lang/driver/src/info/data.rs, lang/lsp/src/hover.rs
Just an uninformative "Clause" for now. I also want to add hover information for patterns, but they currently lack spans.
=> Add hover info for individual clause

lang/lowering/src/lower/decls/mod.rs, lang/lowering/src/lower/exp/mod.rs, lang/lowering/src/result.rs, lang/lowering/src/symbol_table/build.rs, lang/parser/src/cst/exp.rs, lang/parser/src/grammar/cst.lalrpop, lang/parser/src/lexer/mod.rs, test/suites/fail-lower/L-015.expected, test/suites/fail-lower/L-015.pol, test/suites/fail-lower/L-016a.expected, test/suites/fail-lower/L-016a.pol, test/suites/fail-lower/L-016b.expected, test/suites/fail-lower/L-016b.pol, test/suites/fail-lower/L-016c.expected, test/suites/fail-lower/L-016c.pol, test/suites/fail-lower/L-016d.expected, test/suites/fail-lower/L-016d.pol, test/suites/fail-lower/L-016e.expected, test/suites/fail-lower/L-016e.pol, test/suites/fail-lower/L-016f.expected, test/suites/fail-lower/L-016f.pol
Fixes #439 
Simplifies the parser, and is also forwards compatible if we ever want to pass arguments to type universes. (E.g. `Type(0)`, `Type(1)` etc.
=> Remove type cst

lang/elaborator/README.md, lang/elaborator/src/conversion_checking/unify.rs, lang/elaborator/src/typechecker/exprs/anno.rs, lang/elaborator/src/typechecker/exprs/call.rs, lang/elaborator/src/typechecker/exprs/dot_call.rs, lang/elaborator/src/typechecker/exprs/local_match.rs, lang/elaborator/src/typechecker/exprs/typ_ctor.rs, lang/elaborator/src/typechecker/exprs/type_univ.rs, lang/elaborator/src/typechecker/exprs/variable.rs, lang/elaborator/src/typechecker/util.rs
Removes all mentions of `unificator` in `conversion_checking`.
=> Simplify conversion checking

lang/elaborator/src/conversion_checking/constraints.rs, lang/elaborator/src/conversion_checking/mod.rs, lang/elaborator/src/conversion_checking/unify.rs, lang/elaborator/src/typechecker/exprs/anno.rs, lang/elaborator/src/typechecker/exprs/call.rs, lang/elaborator/src/typechecker/exprs/dot_call.rs, lang/elaborator/src/typechecker/exprs/local_match.rs, lang/elaborator/src/typechecker/exprs/typ_ctor.rs, lang/elaborator/src/typechecker/exprs/type_univ.rs, lang/elaborator/src/typechecker/exprs/variable.rs
This does not change any actual constraint solving logic, it just adds a field `ctx` to all conversion checking constraints. It currently clones the `TypeCtx` used by the typechecker (which is inefficient and needs to be fixed).
=> Add TypeCtx to conversion checking constraints

app/src/cli/lift.rs, lang/driver/src/lift.rs, lang/lsp/src/codeactions.rs
As a preparation to adding a lift code action to the language server, I adjust `Database::lift` to generating edits, rather than the full modified module.
I add an initial lift action that works similar to the xfunc action in that the user can lift all local (co)matches of a type to the top-level.
=> Add lift action to language server

lang/ast/src/decls.rs, lang/ast/src/exp/anno.rs, lang/ast/src/exp/args.rs, lang/ast/src/exp/call.rs, lang/ast/src/exp/case.rs, lang/ast/src/exp/dot_call.rs, lang/ast/src/exp/hole.rs, lang/ast/src/exp/local_comatch.rs, lang/ast/src/exp/local_match.rs, lang/ast/src/exp/mod.rs, lang/ast/src/exp/typ_ctor.rs, lang/ast/src/exp/type_univ.rs, lang/ast/src/exp/variable.rs, lang/ast/src/traits/subst.rs, lang/elaborator/src/conversion_checking/unify.rs, lang/elaborator/src/index_unification/unify.rs, lang/elaborator/src/result.rs, lang/elaborator/src/typechecker/ctx.rs, lang/elaborator/src/typechecker/exprs/call.rs, lang/elaborator/src/typechecker/exprs/dot_call.rs, lang/elaborator/src/typechecker/exprs/local_comatch.rs, lang/elaborator/src/typechecker/exprs/local_match.rs, lang/elaborator/src/typechecker/exprs/mod.rs, lang/transformations/src/lifting/mod.rs, lang/transformations/src/lifting/signature.rs
In preparation of fixing the unification implementation that is part of conversion checking, I make substitutions fallible. Thereafter I can implement a `PartialRenaming` substitution which can fail if it encounters a variable that is not in its domain.
Alternatives include creating a separate fallible AST traversal for partial renaming or a traversal to check for free variables. However, I think that this approach is both the most efficient and future-proof, because it allows us to relax some rigidity conditions by executing them lazily as part of the fallible substitution.
Open question: I added some `unwrap`s in places where the substitution result is known to be infallible (and where currently no `Result` can be propagated. This is not ideal, because it is not statically verified that …
=> Make substitution fallible

lang/ast/src/ctx/values.rs, lang/ast/src/decls.rs, lang/ast/src/exp/hole.rs, lang/ast/src/traits/occurs.rs, lang/driver/src/database.rs, lang/elaborator/src/conversion_checking/mod.rs, lang/elaborator/src/conversion_checking/unify.rs, lang/elaborator/src/normalizer/eval.rs, lang/elaborator/src/normalizer/val.rs, lang/elaborator/src/result.rs, lang/elaborator/src/typechecker/decls/mod.rs, std/data/eq.pol, test/suites/fail-check/011-escaping-hole.expected, test/suites/fail-check/011-escaping-hole.pol, test/suites/fail-check/Regr-348.expected, test/suites/fail-check/Regr-348.pol, test/suites/fail-check/Regr-403.expected, test/suites/fail-check/Regr-403.pol, test/suites/success/039-metavars-accross-decls.ir.expected, test/suites/success/039-metavars-accross-decls.pol, test/suites/success/Regr-348.ir.expected, test/suites/success/Regr-348.pol, test/suites/success/Regr-403.pol, test/suites/success/Regr-442.ir.expected, test/suites/success/Regr-442.pol
Previous to this PR, our implementation of unification for conversion checking was incorrect because we did not properly build an inverse substitution for the hole arguments.
This led to bugs such as #442 and #348.
Depends on #479 and #480.
Fixes #442, fixes #348.
=> Fix unification for conversion checking

lang/ast/src/decls.rs, lang/elaborator/src/conversion_checking/unify.rs, test/suites/fail-check/012-nonlinear-args.expected, test/suites/fail-check/012-nonlinear-args.pol
The first baby step to relax the conditions on metavariable arguments: we allow non-linear arguments if they don't occur in the solution.
We still need to improve the error messages here.
=> Allow non-linear arguments that don't occur in solution

Cargo.lock, app/Cargo.toml, app/src/cli/lex.rs, app/src/cli/mod.rs, lang/parser/src/lib.rs
Small CLI option to get the token stream for a file. Useful for working on the lexer or debugging lexing issues.
```console
david@edueeb6 polarity % pol lex std/codata/fun.pol
DocComment("-- | The type of non-dependent functions.\n") at (0,42)
Codata at (42,48)
Ident("Fun") at (49,52)
LParen at (52,53)
Ident("a") at (53,54)
Ident("b") at (55,56)
Colon at (56,57)
Ident("Type") at (58,62)
RParen at (62,63)
LBrace at (64,65)
DocComment("-- | Application of a function to its argument.\n") at (70,118)
Ident("Fun") at (122,125)
LParen at (125,126)
Ident("a") at (126,127)
Comma at (127,128)
Ident("b") at (129,130)
RParen at (130,131)
Dot at (131,132)
Ident("ap") at (132,134)
LParen at (134,135)
Implicit at (135,143)
Ident("a") at (144,145)
Ident("b") at (146,147)
Colon at (147,148)
Ident("Type") …
```
=> Add CLI option to test lexer

Cargo.lock, Cargo.toml, app/Cargo.toml, app/src/cli/lsp.rs, contrib/nix/package.nix, lang/lsp/Cargo.toml, lang/lsp/src/capabilities.rs, lang/lsp/src/codeactions.rs, lang/lsp/src/conversion/mod.rs, lang/lsp/src/conversion/uri_to_url.rs, lang/lsp/src/diagnostics.rs, lang/lsp/src/format.rs, lang/lsp/src/gotodefinition.rs, lang/lsp/src/hover.rs, lang/lsp/src/server.rs, web/crates/browser/Cargo.toml, web/crates/browser/src/lib.rs
The fork has renamed the library from `tower-lsp` to `tower-lsp-server`.
=> Follow renaming of tower-lsp-community fork

examples/stlc.pol, lang/ast/src/exp/local_comatch.rs, lang/lowering/src/lower/exp/mod.rs, lang/parser/src/cst/exp.rs, lang/parser/src/grammar/cst.lalrpop, test/suites/fail-check/Regr-403.expected, test/suites/fail-check/Regr-403.pol, test/suites/success/008.pol, test/suites/success/009.pol, test/suites/success/010.pol, test/suites/success/035-stlc-bool.pol, test/suites/success/036-webserver.pol, test/suites/success/040-absurd-lam.pol, test/suites/success/Regr-341a.pol, test/suites/success/Regr-403.pol
Before this PR we have syntactic sugar for lambda abstractions which looks like `\x. e` and is desugared to `cocase { ap(_,_,x) => e }`. The downside of this approach is that we bake in the dependency on one specific codata type `Fun` with one specific destructor `ap`. But this kind of sugar would also be useful for other codata types with exactly one destructor, for example `Pi` with its destructor `dap`.
This PR changes the syntax sugar to allow `\d(args) => e` which is desugared to `cocase { d(args) => e }`. For the function type this results in `\ap(_,_,x) => e`, but as soon as we allow to omit implicit arguments in patterns we can write this as `\ap(x) => e` which is reasonably short.
As soon as we have nested patterns, we can also allow, for example `\ap(Tup(x,y)) => e`...
(SAM …
=> Revisit lambda sugar for arbitrary SAM

examples/strong_existentials.pol, lang/lowering/src/lower/exp/mod.rs, lang/lowering/src/result.rs, lang/parser/src/cst/exp.rs, lang/parser/src/cst/ident.rs, lang/parser/src/grammar/cst.lalrpop, lang/parser/src/lexer/mod.rs, test/suites/fail-lower/L-017.expected, test/suites/fail-lower/L-017.pol, test/suites/fail-parse/P-003.expected, test/suites/success/036-webserver.pol, test/suites/success/Regr-250.ir.expected, test/suites/success/Regr-250.pol
Modify the lexer so that we have separate productions for identifiers and operators. I am not sure which other Unicode categories we might want to add for operators, but `Sm` is already quite big, and contains most of the mathy stuff. In order to make operators distinct from identifiers I removed `Sm` from the syntax of identifiers. An alternative would be to not allow identifiers to *start* with a character from the `Sm` set.
=> Add lexer for operators

examples/index.json, examples/set.pol, std/data/nat.pol, std/data/ordering.pol
I originally implemented this as a [gist](https://gist.github.com/brendanzab/285c31f1c5dc9da954cd48c8fbee47b7), and was asked on discord if I could add this as an example to the repository because “it is a non-(strictly positive) codata type (in the `.union` destructor `Set` occurs both positively and negatively in recursive positions)”.
I wasn’t sure if I should keep it self-contained, or if I should use the prelude. I ultimately ended up using the prelude and adding `Nat.eq`, but this could be changed. I could also bring the definitions more into the line by using the relational operations on `Bool`, but I was unsure if they were lazily evaluated or not, so left the example using `match` for now.
Edit: I decided to switch to using the boolean operations, as it makes the example much …
=> Add example of set objects

Makefile
`cargo install` doesn't respect the lockfile `Cargo.lock` by default. This is why `make install` always tries to connect to the internet to update dependencies. With this patch `make install` should work reliably offline if the dependencies are cached.
=> Respect lockfile in install target

test/test-runner/src/main.rs, test/test-runner/src/runner.rs
Fixes https://github.com/polarity-lang/polarity/issues/513
=> Test runner returns zero exit code if all failures are resolved by --update-expected

lang/ast/src/ctx/def.rs, lang/ast/src/ctx/values.rs, lang/driver/src/info/data.rs, lang/elaborator/src/conversion_checking/mod.rs, lang/elaborator/src/typechecker/ctx.rs, lang/elaborator/src/typechecker/exprs/local_match.rs, lang/elaborator/src/typechecker/exprs/mod.rs, lang/transformations/src/lifting/fv.rs
Prerequisite for any of the following:
* Reduce metavariable context by not including variables refined by pattern matching
* Implement let bindings
* Lazy substitutions
Although, right now I'm focusing on the first point. Could therefore remove the `LetBinding` variant for now if you prefer.
=> Store values in TypeCtx

test/suites/fail-check/013-eta-comatch.expected, test/suites/fail-check/013-eta-comatch.pol, test/suites/success/040-absurd-lam.ir.expected, test/suites/success/041-eta-comatch.ir.expected, test/suites/success/041-eta-comatch.pol
I'm not sure if this is good enough, because the successful case should really compute and then trigger the shortcut syntactic equality rule.
But since there's no shortcut rule in the conversion checker atm, this does the job.
=> Add test cases on eta for co-matches

lang/driver/src/result.rs, lang/lowering/src/ctx.rs, lang/lowering/src/lib.rs, lang/lowering/src/lower/decls/codata_declaration.rs, lang/lowering/src/lower/decls/codefinition.rs, lang/lowering/src/lower/decls/data_declaration.rs, lang/lowering/src/lower/decls/definition.rs, lang/lowering/src/lower/decls/infix_declaration.rs, lang/lowering/src/lower/decls/mod.rs, lang/lowering/src/lower/decls/toplevel_let.rs, lang/lowering/src/lower/exp/anno.rs, lang/lowering/src/lower/exp/args.rs, lang/lowering/src/lower/exp/binop.rs, lang/lowering/src/lower/exp/call.rs, lang/lowering/src/lower/exp/dot_call.rs, lang/lowering/src/lower/exp/hole.rs, lang/lowering/src/lower/exp/lam.rs, lang/lowering/src/lower/exp/local_comatch.rs, lang/lowering/src/lower/exp/local_match.rs, lang/lowering/src/lower/exp/mod.rs, lang/lowering/src/lower/exp/nat_lit.rs, lang/lowering/src/lower/mod.rs, lang/lowering/src/result.rs, lang/lowering/src/symbol_table/build.rs, lang/lowering/src/symbol_table/lookup.rs, lang/parser/src/cst/mod.rs
This is in preparation for emitting more than one error during lowering. Emitting more than one lowering error at a time should be a huge usability improvement.
=> Refactor lowering errors

lang/docs/src/render/html.rs, lang/printer/src/render/latex.rs, lang/printer/src/render/termcolor.rs
Fix warnings for new clippy hints that were introduced in Rust 1.87
=> Fix warnings for clippy 1.87.0

lang/lowering/src/lower/exp/mod.rs, lang/lowering/src/lower/exp/parens.rs, lang/parser/src/cst/exp.rs, lang/parser/src/grammar/cst.lalrpop
I will need a proper representation of  parenthesized expressions in lowering later, if we want to implement associativity and precedence for binary operators.
=> Add cst node for parenthesized expressions

lang/ast/src/exp/local_let.rs, lang/ast/src/exp/mod.rs, lang/backend/src/ast2ir/exprs.rs, lang/driver/src/info/collect.rs, lang/elaborator/src/normalizer/eval.rs, lang/elaborator/src/typechecker/erasure.rs, lang/elaborator/src/typechecker/exprs/mod.rs, lang/printer/src/tokens.rs, lang/transformations/src/lifting/fv.rs, lang/transformations/src/lifting/mod.rs
This PR adds local let expressions to the AST, implementing the necessary traits implemented for `ast::Exp`. It leaves TODOs in form of `todo!()`s or internal (`Impossible`) error messages in other places.
=> Add local let expressions to ast

contrib/nix/shell.nix
Without it I kept getting
```
rust-analyzer failed to load workspace: Failed to find sysroot for Cargo.toml file ~/project/Cargo.toml. Is rust-src installed?: can't load standard library from sysroot /nix/store/<hash>-rustc-1.86.0 (discovered via `rustc --print sysroot`) try installing the Rust source the same way you installed rustc
```
=> Add an env variable to shell.nix for VS Code and rust-analyzer

lang/driver/src/database.rs, test/test-runner/src/phases.rs, test/test-runner/src/runner.rs
There were newly added clippy lints in 1.88.0.
Some were already addressed (#537) but some were missing and CI complained.
=> Fix missing clippy linting errors

lang/elaborator/src/conversion_checking/unify.rs, lang/parser/src/lexer/mod.rs
When I generated documentation for the Rust crates, Cargo complained about URLs in doc-comments that were not formatted correctly, so I fixed it.
Now, the URLs get generated as actual hyperlinks in the documentation.
=> Fix hyperlink format of URLs in doc-comments

lang/ast/src/decls.rs, lang/parser/src/grammar/cst.lalrpop
We allow empty lines in doc-comments (which seems reasonable for structuring comments):
```
/// First line
/// Second line
data Bool { T, F }
```
But the parser trims those empty lines away. That's why the are "forgotten" when e.g. format-printing or in documentation.
The previous example would be formatted as:
```
/// First line
/// Second line
data Bool { T, F }
```
With these changes, the parser stores empty lines as well and prints empty doc-comment lines without trailing space.
The example would be formatted like so:
```
/// First line
///
/// Second line
data Bool { T, F }
```
Note that the empty line is prefixed with `///` which IMO is a reasonable default because the doc-comment can be recognized as a unit.
=> Pretty printing of empty doc-comment lines

lang/ast/src/exp/local_comatch.rs, lang/ast/src/exp/local_match.rs, lang/elaborator/src/normalizer/val.rs, lang/elaborator/src/typechecker/exprs/local_match.rs, lang/lowering/src/lower/exp/local_match.rs, lang/transformations/src/lifting/mod.rs
Add closure field to `LocalMatch` and also fix some implementations for `LocalComatch` that no longer went in the `cases` even though this is still needed.
=> Add closure field to LocalMatch

lang/ast/src/exp/local_let.rs
When we substitute in the body of a local let expression then we need to shift the body of the substitution by one.
=> Fix substitution for local let expressions

Cargo.toml
When skimming through the repository, I noticed this little typo.
=> Fix repository link in Cargo.toml
