polarity-lang/polarity

lang/printer/src/tokens.rs, lang/printer/src/types.rs, lang/printer/src/ust.rs
=> Implement prettyprinting of attributes

lang/query/src/info.rs
This PR replaces the info collector which uses the generic visitor with a handwritten traversal.
There are only two uses of the generic visitor in the entire codebase, and this is one of them.
=> Replace the visitor in the info collector with handwritten traversal

app/src/cli/format.rs, app/src/cli/lift.rs, app/src/cli/texify.rs, lang/elaborator/src/normalizer/eval.rs, lang/elaborator/src/normalizer/normalize.rs, lang/elaborator/src/normalizer/read_back.rs, lang/elaborator/src/typechecker/ctx.rs, lang/elaborator/src/typechecker/decls.rs, lang/elaborator/src/typechecker/typecheck.rs, lang/elaborator/src/typechecker/util.rs, lang/lifting/src/lib.rs, lang/lowering/src/lib.rs, lang/parser/src/cst/decls.rs, lang/parser/src/grammar/cst.lalrpop, lang/parser/src/lib.rs, lang/printer/src/fragments.rs, lang/printer/src/generic.rs, lang/query/src/info/collect.rs, lang/query/src/view/lift.rs, lang/query/src/view/rt.rs, lang/query/src/view/xfunc.rs, lang/renaming/src/ast.rs, lang/syntax/src/trees/generic/decls.rs, lang/syntax/src/trees/generic/lookup.rs, lang/xfunc/src/lib.rs, lang/xfunc/src/matrix.rs, test/test-runner/src/phases.rs
#198 is still WIP, but we can merge these two commits already.
=> Simplify modules prelim

lang/elaborator/src/normalizer/env.rs, lang/elaborator/src/normalizer/eval.rs, lang/elaborator/src/normalizer/read_back.rs, lang/elaborator/src/normalizer/val.rs
Use the same structure and naming scheme as the generic AST. (They diverged a bit over time)
=> Refactor normalizer

lang/query/src/info/collect.rs, lang/query/src/info/data.rs, util/lsp/src/hover.rs
Shows the doccomments for calls, dotcalls and typctors on hover.
=> Show doc-comments on hover

lang/elaborator/src/typechecker/typecheck.rs, lang/elaborator/src/unifier/unify.rs
Start by removing two instances which stand in the way.
=> Fix unifier eqns

lang/elaborator/src/normalizer/eval.rs, lang/elaborator/src/typechecker/typecheck.rs, lang/lowering/src/lower/exp.rs, lang/syntax/src/trees/ast/lookup.rs, test/suites/fail-check/005.expected, test/suites/fail-check/005.pol, test/suites/success/015.pol
=> Lower, typecheck, and normalize let bindings

lang/elaborator/src/normalizer/eval.rs, lang/lifting/src/lib.rs, lang/lowering/src/lower/decls.rs, lang/parser/src/cst/decls.rs, lang/parser/src/grammar/cst.lalrpop, lang/printer/src/generic.rs, lang/syntax/src/trees/ast/decls.rs, lang/syntax/src/trees/ast/lookup.rs, lang/xfunc/src/matrix.rs
=> Centralize definition of possible attributes

lang/elaborator/src/normalizer/eval.rs
We are losing some traces for eval, but these were misleading before: Even if you would evaluate a global comatch `C(...).d(...)` it would create a trace `comatch {..}.d(...)`.
=> Inline beta_(co)match and improve docs

lang/elaborator/src/typechecker/decls/codefinition.rs, lang/elaborator/src/typechecker/exprs/local_comatch.rs, lang/elaborator/src/typechecker/exprs/mod.rs, test/suites/success/Regression-250.pol
=> Add regression test for bug #250

test/test-runner/src/phases.rs
Fixes #254 
Panics in the compiler are currently not caught in the testsuite driver. This commit uses catch_unwind to catch any panics that are due to bugs in the compiler. This allows to display multiple failing tests.
Example output:
```console
thread 'main' panicked at lang/elaborator/src/typechecker/exprs/variable.rs:21:9:
not yet implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at lang/elaborator/src/typechecker/exprs/variable.rs:21:9:
not yet implemented
thread 'main' panicked at lang/elaborator/src/typechecker/exprs/variable.rs:21:9:
not yet implemented
thread 'main' panicked at lang/elaborator/src/typechecker/exprs/variable.rs:21:9:
not yet implemented
thread 'main' panicked at …
```
=> Catch panics in the testsuite driver

Cargo.lock, Cargo.toml, app/Cargo.toml, lang/elaborator/Cargo.toml, lang/lifting/Cargo.toml, lang/lowering/Cargo.toml, lang/lsp/Cargo.toml, lang/miette_util/Cargo.toml, lang/parser/Cargo.toml, lang/printer/Cargo.toml, lang/query/Cargo.toml, lang/renaming/Cargo.toml, lang/syntax/Cargo.toml, lang/syntax/src/ast/decls.rs, lang/syntax/src/ast/traits/leveled.rs, lang/syntax/src/ast/traits/shift.rs, lang/xfunc/Cargo.toml, lang/xfunc/src/matrix.rs
We didn't have package metadata for the anonymized submission, but we are no longer anonymous.
=> Inherit crate metadata from workspace

README.md, web/LICENSE, web/README.md
=> Relicense web demo

.github/workflows/deploy.yml
Whenever a new version of the web demo has been built and uploaded on main, we want to automatically trigger a redeployment of the website.
=> Trigger deployment of web demo

README.md
Small leftover work from last PR.
=> Adjust readme to correspond to directories in lang/

lang/ast/src/decls.rs, lang/ast/src/exp.rs, lang/ast/src/traits/mod.rs, lang/ast/src/traits/named.rs
Simple little cleanup in the `ast` crate.
=> Factor out the Named trait

Cargo.lock, test/test-runner/Cargo.toml, test/test-runner/src/runner.rs
Works on Mac and Linux :)
Hopefully it doesn't fail in CI, but we will see.
=> Add colored output to testsuite driver

Cargo.lock, lang/ast/src/decls.rs, lang/ast/src/ident.rs, lang/ast/src/traits/subst.rs, lang/elaborator/src/normalizer/env.rs, lang/elaborator/src/normalizer/val.rs, lang/elaborator/src/typechecker/exprs/local_comatch.rs, lang/elaborator/src/typechecker/exprs/local_match.rs, lang/elaborator/src/typechecker/exprs/mod.rs, lang/lifting/src/lib.rs, lang/lowering/src/ctx.rs, lang/lowering/src/lower/decls/codata_declaration.rs, lang/lowering/src/lower/decls/codefinition.rs, lang/lowering/src/lower/decls/data_declaration.rs, lang/lowering/src/lower/decls/definition.rs, lang/lowering/src/lower/decls/mod.rs, lang/lowering/src/lower/decls/toplevel_let.rs, lang/lowering/src/lower/exp/mod.rs, lang/parser/Cargo.toml, lang/parser/src/cst/ident.rs, lang/parser/src/grammar/cst.lalrpop, lang/query/src/xfunc.rs, lang/renaming/src/ctx.rs, lang/renaming/src/util.rs
Does what it says on the tin :)
=> Add span to idents

app/tests/integration_test.rs, lang/query/src/database.rs
Fixes `pol check examples/imports.pol`.
=> Fix pol check with imports

test/test-runner/src/phases.rs
Small simplification: We don't have to handle the lookup tables since the driver takes care of that.
=> Simplify testsuite driver

lang/ast/src/decls.rs, lang/driver/src/edit.rs, lang/driver/src/xfunc.rs, lang/lifting/src/lib.rs, lang/lowering/src/lib.rs, lang/parser/src/cst/mod.rs, lang/xfunc/src/matrix.rs, test/test-runner/src/phases.rs, test/test-runner/src/runner.rs
=> Add xfunc tests and fix bugs in xfunc

lang/driver/src/database.rs, lang/driver/src/xfunc.rs, lang/lifting/src/lib.rs, lang/renaming/src/ast.rs
Seems to run through without errors. But I want to proof read before it is ready to merge.
=> Use inplace mutation for renaming

lang/ast/src/decls.rs, lang/ast/src/exp.rs, lang/ast/src/traits/contains_metavars.rs, lang/ast/src/traits/mod.rs, lang/ast/src/traits/zonk.rs, lang/elaborator/src/typechecker/ctx.rs, lang/elaborator/src/typechecker/decls/mod.rs, lang/elaborator/src/typechecker/exprs/hole.rs, lang/elaborator/src/unifier/unify.rs, test/suites/success/Regr-297.pol
=> Zonk in unify

app/src/cli/format.rs
This option is useful for debugging
=> Add "pol fmt --checked" option

web/package-lock.json, web/packages/app/src/editor/language.ts
=> Implement formatting in webdemo

.github/workflows/ci.yml, Makefile, scripts/git-hooks/pre-commit, test/test-runner/Cargo.toml, test/test-runner/src/main.rs
Fixes #361
Works in principle, but I have to check some details...
=> Run testsuite via `cargo test --all`

examples/boolrep.pol, lang/ast/src/ctx/def.rs, lang/ast/src/decls.rs, lang/driver/src/database.rs, lang/driver/src/xfunc.rs, lang/elaborator/src/normalizer/env.rs, lang/elaborator/src/normalizer/eval.rs, lang/elaborator/src/normalizer/normalize.rs, lang/elaborator/src/normalizer/val.rs, lang/elaborator/src/typechecker/ctx.rs, lang/elaborator/src/typechecker/decls/codefinition.rs, lang/elaborator/src/typechecker/decls/definition.rs, lang/elaborator/src/typechecker/decls/global_let.rs, lang/elaborator/src/typechecker/exprs/anno.rs, lang/elaborator/src/typechecker/exprs/call.rs, lang/elaborator/src/typechecker/exprs/dot_call.rs, lang/elaborator/src/typechecker/exprs/local_comatch.rs, lang/elaborator/src/typechecker/exprs/local_match.rs, lang/elaborator/src/typechecker/exprs/mod.rs, lang/elaborator/src/typechecker/type_info_table/build.rs, lang/elaborator/src/typechecker/type_info_table/lookup.rs, lang/elaborator/src/typechecker/type_info_table/mod.rs, test/test-runner/src/phases.rs
=> Support normalizing definitions from other modules

.github/workflows/coverage.yml, app/src/cli/texify.rs, lang/printer/src/render/latex.rs
Just copying some small refactorings from another project. I also (hopefully) fixed the problem with codecov blocking PRs.
=> Small refactorings

Cargo.lock, lang/driver/Cargo.toml, lang/driver/src/database.rs, lang/driver/src/lib.rs, lang/driver/src/result.rs, lang/lsp/src/server.rs, web/crates/browser/Cargo.toml, web/crates/browser/src/lib.rs, web/crates/browser/src/source.rs, web/packages/app/src/editor/app.ts, web/packages/app/webpack.config.js
=> Support imports on wasm

examples/tutorial.pol
I really like it if a tutorial also explains what is going on. I hope that this is correct, a thorough check would be appreciated :) 
See also: https://github.com/polarity-lang/polarity-lang.github.io/pull/10
=> [feat] make the tutorial a bit more tutoring

lang/lowering/src/lower/exp/mod.rs, test/suites/fail-lower/Regr-408.expected, test/suites/fail-lower/Regr-408.pol
=> Point to correct location for missing arguments

web/Makefile
See https://github.com/polarity-lang/polarity/actions/runs/12236629364/job/34130512690.
=> Fix web deployment

.github/workflows/lint.yml, Cargo.lock, app/Cargo.toml, lang/docs/Cargo.toml, lang/docs/src/doc.rs, lang/docs/src/generate.rs, lang/docs/src/generate_docs.rs, lang/docs/src/lib.rs, lang/docs/templates/codata.html, lang/docs/templates/codef.html, lang/docs/templates/data.html, lang/docs/templates/def.html, lang/docs/templates/let.html, lang/docs/templates/module.html, lang/docs/templates/style.css
This PR introduces HTML generation with Askama.
- Added new templates for different declaration types.
- Added a new module that handles the generation of HTML files from the provided input data.
- resolved requested changes from #401
=> Generate html

lang/elaborator/src/index_unification/unify.rs, lang/elaborator/src/typechecker/exprs/local_comatch.rs, lang/elaborator/src/typechecker/exprs/local_match.rs
Remove meta vars handling and rigid flag from index unification.
=> Simplify index unification

Cargo.lock, lang/ast/src/decls.rs, lang/ast/src/exp/local_comatch.rs, lang/ast/src/exp/telescope_inst.rs, lang/ast/src/ident.rs, lang/driver/src/info/data.rs, lang/lowering/Cargo.toml, lang/lowering/src/lower/decls/mod.rs, lang/lowering/src/lower/exp/mod.rs, lang/lowering/src/result.rs, lang/lsp/src/hover.rs, lang/transformations/src/renaming/ctx.rs, lang/transformations/src/renaming/util.rs
Add the distinction between unavailable and available binding sites to the ast
=> Fix var bind

lang/elaborator/src/normalizer/env.rs, lang/elaborator/src/normalizer/eval.rs, lang/elaborator/src/normalizer/val.rs
No longer implements `Context`.
=> Refactor env

Cargo.lock, examples/stlc.pol, lang/docs/Cargo.toml, lang/docs/src/generate.rs, lang/docs/templates/style.css
**Summary**  
- Introduces markdown compatibility for comments 
- normal color palette
=> make comments markdown compatible

Cargo.lock, lang/driver/src/database.rs, lang/driver/src/dependency_graph.rs, web/README.md, web/crates/browser/Cargo.toml, web/crates/browser/src/lib.rs, web/package-lock.json, web/packages/app/src/editor/app.ts, web/packages/app/src/editor/server.ts
This PR also:
* makes debugging such issues easier by conditionally showing driver logs in the web console
* adds a troubleshooting section for OOM issues with webpack
* updates `package-lock.json` to the result of running `npm audit fix`
=> Fix imports in the web demo

lang/docs/templates/style.css
**Summary**  
- Replace color theme with arctic blue palette
=> Change color palette

ARCHITECTURE.md, CONTRIBUTING.md, Cargo.lock, Cargo.toml, Makefile, bench/Cargo.toml, bench/src/main.rs
This PR adds the skeleton of a benchmark suite. Main problem is that we measure disc IO in the benchmark, so we should probably first read in the file in the database before taking the measurement.
=> Implement benchmarks

lang/ast/src/exp/anno.rs, lang/ast/src/exp/args.rs, lang/ast/src/exp/call.rs, lang/ast/src/exp/case.rs, lang/ast/src/exp/dot_call.rs, lang/ast/src/exp/hole.rs, lang/ast/src/exp/local_comatch.rs, lang/ast/src/exp/local_match.rs, lang/ast/src/exp/mod.rs, lang/ast/src/exp/typ_ctor.rs, lang/ast/src/exp/type_univ.rs, lang/ast/src/exp/variable.rs, lang/ast/src/traits/occurs.rs, lang/elaborator/src/typechecker/util.rs, lang/transformations/src/lifting/signature.rs
Generalize occurs check as a preparation to adding an occurs check for metavariables.
=> Generalize occurs check

lang/elaborator/src/conversion_checking/constraints.rs, lang/elaborator/src/conversion_checking/mod.rs, lang/elaborator/src/conversion_checking/unify.rs, lang/elaborator/src/typechecker/exprs/anno.rs, lang/elaborator/src/typechecker/exprs/call.rs, lang/elaborator/src/typechecker/exprs/dot_call.rs, lang/elaborator/src/typechecker/exprs/local_match.rs, lang/elaborator/src/typechecker/exprs/typ_ctor.rs, lang/elaborator/src/typechecker/exprs/type_univ.rs, lang/elaborator/src/typechecker/exprs/variable.rs
Don't clone type contexts if a reference will do.
=> Dont clone typectxts

lang/ast/src/decls.rs, lang/driver/src/info/lookup.rs, lang/driver/src/lift.rs, lang/driver/src/xfunc.rs, lang/elaborator/src/typechecker/decls/mod.rs, lang/transformations/src/lifting/mod.rs
Some refactorings to unblock #509 where we add a new kind of toplevel declaration.
=> Refactor ident function

lang/ast/src/ctx/def.rs, lang/driver/src/database.rs, lang/driver/src/dependency_graph.rs, lang/elaborator/src/conversion_checking/unify.rs
CI is currently not running through due to new lints that were added to clippy
=> Fix newly introduced clippy hints

flake.lock
=> [chore] bump flake lock to get new cargo version

app/src/cli/format.rs
I find it useful being able to format multiple files with a single command:
```bash
pol fmt --inplace examples/*.pol
```
This PR implements this.
=> Support formatting multiple files at once
